# Generated by Django 5.2.13 on 2026-04-30 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_player_deaths_remove_player_kills_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupX1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=20, unique=True)),
                ("ordem", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Grupo X1",
                "verbose_name_plural": "Grupos X1",
                "ordering": ["ordem", "nome"],
            },
        ),
        migrations.AddField(
            model_name="player",
            name="grupo_x1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jogadores",
                to="core.groupx1",
            ),
        ),
        migrations.CreateModel(
            name="X1Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PONTOS_CORRIDOS", "Pontos Corridos"),
                            ("MATA_MATA", "Mata Mata"),
                        ],
                        default="PONTOS_CORRIDOS",
                        max_length=20,
                    ),
                ),
                ("rounds_jogador1", models.IntegerField()),
                ("rounds_jogador2", models.IntegerField()),
                ("prorrogacao", models.BooleanField(default=False)),
                ("rodada", models.IntegerField(blank=True, null=True)),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "jogador1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="x1_partidas_como_j1",
                        to="core.player",
                    ),
                ),
                (
                    "jogador2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="x1_partidas_como_j2",
                        to="core.player",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partida X1",
                "verbose_name_plural": "Partidas X1",
                "ordering": ["-data"],
            },
        ),
        migrations.CreateModel(
            name="X1MatchPlayerStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kills", models.IntegerField(default=0)),
                ("deaths", models.IntegerField(default=0)),
                (
                    "jogador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="x1_match_stats",
                        to="core.player",
                    ),
                ),
                (
                    "partida",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="core.x1match",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estatística de Partida X1",
                "verbose_name_plural": "Estatísticas de Partida X1",
                "unique_together": {("partida", "jogador")},
            },
        ),
    ]
