# Generated by Django 5.2.13 on 2026-04-28 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Duo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=80, unique=True)),
            ],
            options={
                "verbose_name": "Dupla",
                "verbose_name_plural": "Duplas",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, unique=True)),
                ("kills", models.IntegerField(default=0)),
                ("deaths", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Jogador",
                "verbose_name_plural": "Jogadores",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PONTOS_CORRIDOS", "Pontos Corridos"),
                            ("MATA_MATA", "Mata Mata"),
                        ],
                        default="PONTOS_CORRIDOS",
                        max_length=20,
                    ),
                ),
                ("rounds_dupla1", models.IntegerField()),
                ("rounds_dupla2", models.IntegerField()),
                ("prorrogacao", models.BooleanField(default=False)),
                ("rodada", models.IntegerField(blank=True, null=True)),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "dupla1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="partidas_como_d1",
                        to="core.duo",
                    ),
                ),
                (
                    "dupla2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="partidas_como_d2",
                        to="core.duo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partida",
                "verbose_name_plural": "Partidas",
                "ordering": ["-data"],
            },
        ),
        migrations.AddField(
            model_name="duo",
            name="jogador1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="duplas_como_j1",
                to="core.player",
            ),
        ),
        migrations.AddField(
            model_name="duo",
            name="jogador2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="duplas_como_j2",
                to="core.player",
            ),
        ),
    ]
