# Generated by Django 5.2.13 on 2026-04-28 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="deaths",
        ),
        migrations.RemoveField(
            model_name="player",
            name="kills",
        ),
        migrations.CreateModel(
            name="MatchPlayerStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kills", models.IntegerField(default=0)),
                ("deaths", models.IntegerField(default=0)),
                (
                    "jogador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="match_stats",
                        to="core.player",
                    ),
                ),
                (
                    "partida",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="core.match",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estatística de Partida",
                "verbose_name_plural": "Estatísticas de Partida",
                "unique_together": {("partida", "jogador")},
            },
        ),
    ]
